site_name: Installation Guide

pages:
- Welcome: index.md
- Ubuntu Packages - Essentials: ubuntu-essentials.md
- VPN Setup: vpn.md
- SSH Keys: ssh.md
- Text Editor: text-editor.md
- Git: git.md
- Python: python.md
- R: r.md
- Julia: julia.md
- Snakemake: snakemake.md
- Docker: docker.md
- LaTeX: tex.md
- Pandoc: pandoc.md
- Webscraping: webscraping.md
# - GIS Tools: gis-tools.md
- Miscellany: misc.md
- News: NEWS.md
- Contact: contact.md
- Acknowledgements: acknowledgement.md

theme: readthedocs
markdown_extensions:
  - admonition
